### ISSUE TITLE
Walkthrough - Final Gameplay Script 

### ISSUE THREAD

**Issue by BornRiot** [BornRiot/Python.Udemy.Complete_Python_BootCamp#82]
Completion of the Walkthrough - Final Gameplay Script  Video Lecture and Code Along Assignment.

**Comment by Sanchit112** [comment]
What needs to be done?

**Comment by BornRiot** [comment]
@Sanchit112 Well the overall goal of the project is to create a Python version of the card game War. The project itself involves watching a series of code along videos that goes toward completion of the course. I decided as a way to learn Git and GitHub was through creating an issue for each of the videos in the sections of the course and close out each issue by way of a successful pull request and merge into the main/master branch.  The focus of the project is to get students familiar with using Python classes to build a program.
